ALTER TABLE character_pobs
ADD COLUMN dps BIGINT NOT NULL DEFAULT 0,
ADD COLUMN ehp INT NOT NULL DEFAULT 0,
ADD COLUMN phys_max_hit INT NOT NULL DEFAULT 0,
ADD COLUMN ele_max_hit INT NOT NULL DEFAULT 0,
ADD COLUMN hp INT NOT NULL DEFAULT 0,
ADD COLUMN mana INT NOT NULL DEFAULT 0,
ADD COLUMN es INT NOT NULL DEFAULT 0,
ADD COLUMN armour INT NOT NULL DEFAULT 0,
ADD COLUMN evasion INT NOT NULL DEFAULT 0,
ADD COLUMN xp BIGINT NOT NULL DEFAULT 0,
ADD COLUMN movement_speed INT NOT NULL DEFAULT 0;   