name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image with cache
        run: |
          docker buildx build --push -t ${{ secrets.DOCKER_USERNAME }}/bpl2-backend:latest \
          --cache-to type=registry,ref=${{ secrets.DOCKER_USERNAME }}/bpl2-backend:cache,mode=max \
          --cache-from type=registry,ref=${{ secrets.DOCKER_USERNAME }}/bpl2-backend:cache \
          .
