name: Deploy

on:
  push:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: "1.24"

  #     - name: Run tests
  #       run: go test -count=1 ./...

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Print latest tag
        run: git describe --tags --abbrev=0

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "::set-output name=tag::${TAG#v}"

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bpl2-backend:${{ steps.get_tag.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/bpl2-backend:${{ steps.get_tag.outputs.tag }}

      - name: Notify watchtower
        run: |
          curl -X POST "${{vars.SERVER_URL}}/watchtower/v1/update" -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}"
